w

diff --git a/.github/workflows/lighthuse.yml b/.github/workflows/lighthuse.yml
--- a/.github/workflows/lighthuse.yml
+++ b/.github/workflows/lighthuse.yml
@@ -1,24 +1,19 @@
-name: CI
+name: Build project and run Lighthouse CI
 on: [push]
 jobs:
   lhci:
-    name: Lighthouse
+    name: Lighthouse CI
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v1
+      - name: Use Node.js 10.x
+        uses: actions/setup-node@v1
         with:
-          ref: ${{ github.event.pull_request.head.sha }}
-      - name: Use Node.js 14.x
-        uses: actions/setup-node@v2
-        with:
-          node-version: 14.x
-      - name: npm install, build
+          node-version: 10.x
+      - name: npm install
         run: |
           npm install
-          npm run build
       - name: run Lighthouse CI
         run: |
-          npm install -g @lhci/cli@0.8.x
-          lhci autorun
-        env:
-          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
+          npm install -g @lhci/cli@0.3.x
+          lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
